# Copyright (C) 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Configuration loading and validation."""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field, replace
from typing import Any


class ConfigError(Exception):
    """Raised when the supplied configuration is unusable."""


@dataclass(frozen=True)
class GerritConfig:
    url: str
    username: str
    # Gerrit HTTP auth token. Read from GERRIT_TOKEN when absent from the file.
    token: str
    # Git URL used to fetch refs/changes/*. Defaults to `url`.
    git_url: str = ""
    # Read over the unauthenticated endpoints. Only viable where the instance
    # grants anonymous read, and only ever read: the archiver never writes to
    # Gerrit. Note that anonymous access cannot see private changes at all,
    # which is a safe direction to fail in.
    anonymous: bool = False

    def __post_init__(self) -> None:
        if not self.url:
            raise ConfigError("gerrit.url is required")


@dataclass(frozen=True)
class GitHubConfig:
    owner: str
    repo: str
    # Bot token. Read from GITHUB_TOKEN when absent from the file.
    token: str
    api_url: str = "https://api.github.com"
    # Push URL for the archive branches. Defaults to HTTPS with the token.
    git_url: str = ""

    @property
    def slug(self) -> str:
        return f"{self.owner}/{self.repo}"


@dataclass(frozen=True)
class ProjectMapping:
    """One Gerrit project projected onto one GitHub repository."""

    gerrit_project: str
    github: GitHubConfig
    # Only changes targeting these branches are archived. Empty means all.
    branches: tuple[str, ...] = ()
    # Archive head refs are pushed as <branch_prefix>/<change number>.
    branch_prefix: str = "gerrit-archive"


@dataclass(frozen=True)
class WebhookConfig:
    """Receiver for Gerrit's webhooks plugin.

    Latency optimisation only: the reconciler remains the correctness
    mechanism, because the plugin drops events after a few failed retries.
    """

    enabled: bool = False
    # Bind to loopback by default. The webhooks plugin cannot sign payloads
    # or send custom headers, so the only credential available is whatever
    # is embedded in the URL -- and it defaults to not verifying TLS. Keep
    # the listener off the public network.
    host: str = "127.0.0.1"
    port: int = 8081
    path: str = "/gerrit-event"
    # Shared secret, compared against HTTP basic auth, an X-Archiver-Token
    # header, or a ?token= query parameter. Read from WEBHOOK_TOKEN when
    # absent from the file. Empty disables authentication entirely.
    token: str = ""
    # Each worker gets its own HTTP clients, so more than one is safe; one is
    # usually plenty and makes ordering trivially correct.
    workers: int = 1
    # On overflow events are dropped and the sweep picks them up instead.
    queue_size: int = 1000


@dataclass(frozen=True)
class Config:
    gerrit: GerritConfig
    projects: tuple[ProjectMapping, ...]
    ledger_path: str = "archiver.sqlite3"
    mirror_path: str = "mirror"
    # Reconciler only inspects changes updated within this window. The ledger
    # makes re-inspection cheap, so a generous window costs little and protects
    # against clock skew between Gerrit and the archiver.
    lookback_minutes: int = 180
    poll_interval_seconds: int = 60
    # Gerrit query page size.
    page_size: int = 100
    # Skip messages Gerrit generated itself (patch set uploads and the like)
    # when they carry no inline comments.
    skip_autogenerated_messages: bool = True
    # Never project changes that are private or work-in-progress-and-private.
    # Present as a flag only so tests can exercise the unfiltered path.
    skip_private: bool = True
    dry_run: bool = False
    webhook: WebhookConfig = field(default_factory=WebhookConfig)

    @staticmethod
    def load(path: str) -> "Config":
        with open(path, "r", encoding="utf-8") as fh:
            raw = json.load(fh)
        return Config.from_dict(raw)

    @staticmethod
    def from_dict(raw: dict[str, Any]) -> "Config":
        if "gerrit" not in raw:
            raise ConfigError("missing 'gerrit' section")
        g = dict(raw["gerrit"])
        g.setdefault("token", os.environ.get("GERRIT_TOKEN", ""))
        if not g.get("token") and not g.get("anonymous"):
            raise ConfigError(
                "gerrit token missing (set gerrit.token, GERRIT_TOKEN, or "
                "gerrit.anonymous for an instance that allows anonymous read)"
            )
        g.setdefault("git_url", g["url"])
        gerrit = GerritConfig(**g)

        raw_projects = raw.get("projects") or []
        if not raw_projects:
            raise ConfigError("at least one entry in 'projects' is required")

        projects: list[ProjectMapping] = []
        for entry in raw_projects:
            entry = dict(entry)
            gh = dict(entry.pop("github", {}))
            gh.setdefault("token", os.environ.get("GITHUB_TOKEN", ""))
            if not gh.get("token"):
                raise ConfigError(
                    "github token missing (set projects[].github.token or GITHUB_TOKEN)"
                )
            for required in ("owner", "repo"):
                if not gh.get(required):
                    raise ConfigError(f"projects[].github.{required} is required")
            gh.setdefault(
                "git_url",
                f"https://x-access-token:{gh['token']}@github.com/"
                f"{gh['owner']}/{gh['repo']}.git",
            )
            if not entry.get("gerrit_project"):
                raise ConfigError("projects[].gerrit_project is required")
            entry["branches"] = tuple(entry.get("branches") or ())
            projects.append(ProjectMapping(github=GitHubConfig(**gh), **entry))

        webhook_raw = dict(raw.get("webhook") or {})
        if "token" not in webhook_raw:
            webhook_raw["token"] = os.environ.get("WEBHOOK_TOKEN", "")
        try:
            webhook = WebhookConfig(**webhook_raw)
        except TypeError as exc:
            raise ConfigError(f"invalid 'webhook' section: {exc}") from exc

        top = {
            k: v
            for k, v in raw.items()
            if k not in ("gerrit", "projects", "webhook")
        }
        try:
            return Config(
                gerrit=gerrit,
                projects=tuple(projects),
                webhook=webhook,
                **top,
            )
        except TypeError as exc:
            raise ConfigError(f"unknown configuration key: {exc}") from exc

    def with_dry_run(self) -> "Config":
        return replace(self, dry_run=True)
