// Copyright (C) 2026 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.googlesource.gerrit.plugins.githubarchiver;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import com.google.gerrit.extensions.client.ChangeStatus;
import com.google.gerrit.extensions.common.AccountInfo;
import com.google.gerrit.extensions.common.ChangeInfo;
import com.google.gerrit.extensions.common.ChangeMessageInfo;
import com.google.gerrit.extensions.common.CommentInfo;
import com.google.gerrit.extensions.common.RevisionInfo;
import com.googlesource.gerrit.plugins.githubarchiver.ArchiverConfig.ProjectMapping;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.junit.After;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

/**
 * Convergence behaviour against in-memory doubles.
 *
 * <p>The central property: projecting the same change twice must leave exactly one pull request and
 * one copy of every comment.
 */
public class ProjectorTest {

  private static final String SHA1 = "b".repeat(40);
  private static final String SHA2 = "c".repeat(40);
  private static final Timestamp WHEN = Timestamp.from(Instant.parse("2026-03-14T09:22:33Z"));

  static {
    // The fallback paths log by design; keep test output readable.
    java.util.logging.Logger.getLogger(Projector.class.getName())
        .setLevel(java.util.logging.Level.SEVERE);
  }

  @Rule public TemporaryFolder tmp = new TemporaryFolder();

  private Ledger ledger;
  private Fakes.FakeGitHub github;
  private Fakes.FakeGitOps git;
  private Path ledgerPath;

  /** Config with the injected collaborators stubbed out; only the flags matter here. */
  private static ArchiverConfig config(boolean skipPrivate) {
    return new ArchiverConfig(null, null, null) {
      @Override
      public boolean skipAutogenerated() {
        return true;
      }

      @Override
      public boolean skipPrivate() {
        return skipPrivate;
      }

      @Override
      public String canonicalWebUrl() {
        return "https://gerrit.example.com/";
      }
    };
  }

  private static ProjectMapping mapping(String... branches) {
    return new ProjectMapping(
        "myproject", "o", "r", "gerrit-archive", List.of(branches));
  }

  @Before
  public void setUp() throws Exception {
    ledgerPath = tmp.newFolder().toPath().resolve("ledger.log");
    ledger = new Ledger(ledgerPath);
    github = new Fakes.FakeGitHub();
    git = new Fakes.FakeGitOps();
  }

  @After
  public void tearDown() throws Exception {
    ledger.close();
  }

  private Projector projector() {
    return new Projector(config(true), mapping(), github, git, ledger);
  }

  private static AccountInfo account(int id, String name, String email) {
    AccountInfo a = new AccountInfo(id);
    a.name = name;
    a.email = email;
    return a;
  }

  private static ChangeInfo change() {
    ChangeInfo c = new ChangeInfo();
    c._number = 42;
    c.project = "myproject";
    c.branch = "master";
    c.changeId = "I1234";
    c.subject = "Fix the thing";
    c.status = ChangeStatus.NEW;
    c.created = WHEN;
    c.updated = WHEN;
    c.owner = account(1000, "Alice Smith", "a@x.com");

    RevisionInfo rev = new RevisionInfo();
    rev._number = 1;
    Map<String, RevisionInfo> revs = new LinkedHashMap<>();
    revs.put(SHA1, rev);
    c.revisions = revs;
    c.currentRevision = SHA1;

    ChangeMessageInfo m = new ChangeMessageInfo();
    m.id = "m1";
    m.date = WHEN;
    m.message = "Patch Set 1: Code-Review+2";
    m._revisionNumber = 1;
    m.author = account(1001, "Bob Jones", "b@x.com");
    c.messages = List.of(m);
    return c;
  }

  private static CommentInfo comment(String id, String messageId, Integer line) {
    CommentInfo c = new CommentInfo();
    c.id = id;
    c.path = "src/a.java";
    c.patchSet = 1;
    c.line = line;
    c.updated = WHEN;
    c.message = "needs a null check";
    c.changeMessageId = messageId;
    c.author = account(1001, "Bob Jones", "b@x.com");
    return c;
  }

  private static Map<String, List<CommentInfo>> comments(CommentInfo... cs) {
    Map<String, List<CommentInfo>> out = new LinkedHashMap<>();
    for (CommentInfo c : cs) {
      out.computeIfAbsent(c.path, k -> new ArrayList<>()).add(c);
    }
    return out;
  }

  // -- convergence -----------------------------------------------------

  @Test
  public void firstRunCreatesPrAndReview() throws Exception {
    Projector.Result r = projector().project(change(), comments(comment("c1", "m1", 12)));

    assertTrue(r.createdPr);
    assertEquals(1, r.reviewsPosted);
    assertEquals(1, r.commentsPosted);
    assertEquals(1, github.prs.size());
    assertEquals(1, github.reviews.size());
    assertEquals(1, git.pushes.size());
    assertEquals(SHA1, git.pushes.get(0)[0]);
    assertEquals("gerrit-archive/42", git.pushes.get(0)[1]);
  }

  @Test
  public void secondRunIsANoOp() throws Exception {
    Projector p = projector();
    p.project(change(), comments(comment("c1", "m1", 12)));
    Projector.Result r = p.project(change(), comments(comment("c1", "m1", 12)));

    assertFalse(r.createdPr);
    assertEquals(0, r.reviewsPosted);
    assertEquals(1, github.prs.size());
    assertEquals(1, github.reviews.size());
    assertEquals(1, github.reviewComments.size());
  }

  @Test
  public void newReviewOnSecondRunIsAppended() throws Exception {
    Projector p = projector();
    p.project(change(), comments(comment("c1", "m1", 12)));

    ChangeInfo c = change();
    List<ChangeMessageInfo> messages = new ArrayList<>(c.messages);
    ChangeMessageInfo m2 = new ChangeMessageInfo();
    m2.id = "m2";
    m2.date = WHEN;
    m2.message = "Patch Set 1: Code-Review-1";
    m2._revisionNumber = 1;
    m2.author = account(1002, "Carol", "c@x.com");
    messages.add(m2);
    c.messages = messages;

    Projector.Result r =
        p.project(c, comments(comment("c1", "m1", 12), comment("c2", "m2", 5)));

    assertEquals(1, r.reviewsPosted);
    assertEquals(2, github.reviews.size());
    assertEquals(2, github.reviewComments.size());
  }

  @Test
  public void ledgerLossRecoversViaMarkers() throws Exception {
    // A wiped ledger must not duplicate: adoption re-reads the markers.
    projector().project(change(), comments(comment("c1", "m1", 12)));
    int reviewsBefore = github.reviews.size();

    ledger.close();
    Files.delete(ledgerPath);
    ledger = new Ledger(ledgerPath);

    Projector.Result r = projector().project(change(), comments(comment("c1", "m1", 12)));

    assertEquals(0, r.reviewsPosted);
    assertEquals(reviewsBefore, github.reviews.size());
    assertEquals(1, github.prs.size());
  }

  @Test
  public void reviewBodyWithoutCommentsIsResumed() throws Exception {
    // Simulates dying between posting a review body and its comments.
    Projector p = projector();
    String key = Ledger.changeKey("myproject", 42);
    ledger.upsertChange(key, null, "gerrit-archive/42", null, "NEW");
    ledger.recordSynced(key, Ledger.KIND_MESSAGE, "m1", "999");

    Projector.Result r = p.project(change(), comments(comment("c1", "m1", 12)));

    assertEquals(1, r.commentsPosted);
    // No second review body for the same Gerrit message.
    assertEquals(0, github.reviews.size());
    assertEquals(1, github.reviewComments.size());
  }

  // -- fallbacks -------------------------------------------------------

  @Test
  public void rejectedBatchRetriesPerComment() throws Exception {
    github = new Fakes.FakeGitHub(true, false);
    Projector.Result r =
        projector().project(change(), comments(comment("c1", "m1", 12), comment("c2", "m1", 20)));

    assertEquals(1, r.reviewsPosted);
    assertEquals(2, r.commentsPosted);
    assertEquals(2, github.reviewComments.size());
  }

  @Test
  public void unanchorableCommentBecomesIssueComment() throws Exception {
    github = new Fakes.FakeGitHub(true, true);
    Projector.Result r = projector().project(change(), comments(comment("c1", "m1", 12)));

    assertEquals(1, r.fallbacksPosted);
    assertEquals(1, github.issueComments.size());
    assertTrue(github.issueComments.get(0).get("body").getAsString().contains("null check"));
  }

  @Test
  public void commitMessageCommentSkipsInlineEntirely() throws Exception {
    CommentInfo c = comment("c1", "m1", 7);
    c.path = Projection.COMMIT_MSG;
    Projector.Result r = projector().project(change(), comments(c));

    assertEquals(0, r.commentsPosted);
    assertEquals(1, r.fallbacksPosted);
    assertTrue(github.issueComments.get(0).get("body").getAsString().contains("commit message"));
  }

  // -- visibility ------------------------------------------------------

  @Test
  public void privateChangeIsNeverProjected() throws Exception {
    ChangeInfo c = change();
    c.isPrivate = true;
    Projector.Result r = projector().project(c, Map.of());

    assertEquals("private", r.skippedReason);
    assertTrue(github.prs.isEmpty());
    assertTrue(git.pushes.isEmpty());
  }

  @Test
  public void changeFromAnotherProjectIsRefused() throws Exception {
    ChangeInfo c = change();
    c.project = "other-project";
    Projector.Result r = projector().project(c, Map.of());

    assertTrue(r.skippedReason.contains("not mapped here"));
    assertTrue(github.prs.isEmpty());
  }

  @Test
  public void branchFilterExcludesOtherBranches() throws Exception {
    Projector p = new Projector(config(true), mapping("master"), github, git, ledger);
    ChangeInfo c = change();
    c.branch = "experimental";
    Projector.Result r = p.project(c, Map.of());

    assertTrue(r.skippedReason.contains("not archived"));
    assertTrue(github.prs.isEmpty());
  }

  // -- lifecycle -------------------------------------------------------

  @Test
  public void wipChangeOpensDraftPr() throws Exception {
    ChangeInfo c = change();
    c.workInProgress = true;
    projector().project(c, Map.of());
    assertTrue(github.prs.values().iterator().next().get("draft").getAsBoolean());
  }

  @Test
  public void leavingWipMarksPrReady() throws Exception {
    Projector p = projector();
    ChangeInfo wip = change();
    wip.workInProgress = true;
    p.project(wip, Map.of());
    p.project(change(), Map.of());

    assertEquals(1, github.readyCalls.size());
    assertFalse(github.prs.values().iterator().next().get("draft").getAsBoolean());
  }

  @Test
  public void abandonedChangeClosesPr() throws Exception {
    Projector p = projector();
    p.project(change(), Map.of());
    ChangeInfo c = change();
    c.status = ChangeStatus.ABANDONED;
    p.project(c, Map.of());

    assertEquals("closed", github.prs.values().iterator().next().get("state").getAsString());
  }

  @Test
  public void mergedChangeIsLeftForGitHubToClose() throws Exception {
    // Replication advancing the base branch is what flips the badge to Merged;
    // closing it here would show it as merely Closed.
    Projector p = projector();
    p.project(change(), Map.of());
    ChangeInfo c = change();
    c.status = ChangeStatus.MERGED;
    p.project(c, Map.of());

    assertEquals("open", github.prs.values().iterator().next().get("state").getAsString());
  }

  @Test
  public void newPatchSetForcePushesHead() throws Exception {
    Projector p = projector();
    p.project(change(), Map.of());

    ChangeInfo c = change();
    RevisionInfo r2 = new RevisionInfo();
    r2._number = 2;
    Map<String, RevisionInfo> revs = new LinkedHashMap<>(c.revisions);
    revs.put(SHA2, r2);
    c.revisions = revs;
    c.currentRevision = SHA2;
    p.project(c, Map.of());

    assertEquals(2, git.pushes.size());
    assertEquals(SHA2, git.pushes.get(1)[0]);
    assertEquals("gerrit-archive/42", git.pushes.get(1)[1]);
  }

  @Test
  public void ledgerSurvivesReopen() throws Exception {
    projector().project(change(), comments(comment("c1", "m1", 12)));
    ledger.close();
    ledger = new Ledger(ledgerPath);

    Projector.Result r = projector().project(change(), comments(comment("c1", "m1", 12)));
    assertEquals(0, r.reviewsPosted);
    assertEquals(1, github.reviews.size());
  }
}
