// Copyright (C) 2026 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.googlesource.gerrit.plugins.githubarchiver;

import com.google.gerrit.extensions.annotations.PluginName;
import com.google.gerrit.server.config.PluginConfigFactory;
import com.google.gerrit.server.config.SitePaths;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;
import org.eclipse.jgit.lib.Config;

/**
 * Configuration, split across two files the way the replication plugin splits it.
 *
 * <p>Everything except the credential lives in {@code $site/etc/github-archiver.config}:
 *
 * <pre>
 *   [github]
 *     apiUrl = https://api.github.com
 *   [sweep]
 *     interval = 5 minutes
 *   [project "myproject"]
 *     owner = TheoGoudout
 *     repo = myproject
 *     branchPrefix = gerrit-archive
 *     branch = master          ; repeatable; all branches when absent
 * </pre>
 *
 * <p>The GitHub token lives in {@code $site/etc/secure.config}:
 *
 * <pre>
 *   [plugin "github-archiver"]
 *     githubToken = ghp_...
 * </pre>
 *
 * <p>Reading it through {@link PluginConfigFactory#getFromGerritConfig} is what makes that work:
 * the injected server config is a {@code GerritConfig} wrapping the {@code SecureStore}, so
 * secure.config values resolve transparently. This is the main thing the plugin buys over an
 * external process, which needs its own secret distribution.
 */
@Singleton
public class ArchiverConfig {

  /** One Gerrit project projected onto one GitHub repository. */
  public static class ProjectMapping {
    public final String gerritProject;
    public final String owner;
    public final String repo;
    public final String branchPrefix;
    /** Empty means every branch is archived. */
    public final java.util.List<String> branches;

    ProjectMapping(
        String gerritProject,
        String owner,
        String repo,
        String branchPrefix,
        java.util.List<String> branches) {
      this.gerritProject = gerritProject;
      this.owner = owner;
      this.repo = repo;
      this.branchPrefix = branchPrefix;
      this.branches = branches;
    }

    public String slug() {
      return owner + "/" + repo;
    }

    public String branchFor(int changeNumber) {
      return branchPrefix + "/" + changeNumber;
    }

    public boolean archivesBranch(String branch) {
      return branches.isEmpty() || branches.contains(branch);
    }
  }

  private final String pluginName;
  private final PluginConfigFactory configFactory;
  private final SitePaths sitePaths;

  @Inject
  ArchiverConfig(
      @PluginName String pluginName, PluginConfigFactory configFactory, SitePaths sitePaths) {
    this.pluginName = pluginName;
    this.configFactory = configFactory;
    this.sitePaths = sitePaths;
  }

  private Config own() {
    return configFactory.getGlobalPluginConfig(pluginName);
  }

  /**
   * Returns the GitHub token, or empty when unset.
   *
   * <p>Passing {@code refresh = true} reloads the secure store first, so a rotated token is picked
   * up without restarting Gerrit.
   */
  public Optional<String> githubToken() {
    String token = configFactory.getFromGerritConfig(pluginName, true).getString("githubToken");
    return token == null || token.isEmpty() ? Optional.empty() : Optional.of(token);
  }

  public String githubApiUrl() {
    return own().getString("github", null, "apiUrl") == null
        ? "https://api.github.com"
        : own().getString("github", null, "apiUrl");
  }

  /** Base URL used to build the Gerrit links embedded in archived pull requests. */
  public String canonicalWebUrl() {
    String url = configFactory.getFromGerritConfig("gerrit").getString("canonicalWebUrl");
    return url == null ? "" : url;
  }

  /** Where the ledger is kept. Defaults to {@code $site/data/<plugin>}. */
  public Path dataDir() {
    String configured = own().getString("archiver", null, "dataDir");
    return configured != null && !configured.isEmpty()
        ? Path.of(configured)
        : sitePaths.data_dir.resolve(pluginName);
  }

  /** Gerrit-generated change messages with no comments are skipped by default. */
  public boolean skipAutogenerated() {
    return own().getBoolean("archiver", "skipAutogenerated", true);
  }

  /** Never project private changes. A flag only so tests can exercise the other path. */
  public boolean skipPrivate() {
    return own().getBoolean("archiver", "skipPrivate", true);
  }

  /** Bound on how many changes one sweep will inspect, so a sweep cannot run away. */
  public int sweepLimit() {
    return own().getInt("sweep", "limit", 500);
  }

  /** How far back a sweep looks. The ledger makes re-inspection cheap. */
  public int lookbackMinutes() {
    return own().getInt("sweep", "lookbackMinutes", 180);
  }

  /** Project name to mapping, in config order. */
  public Map<String, ProjectMapping> projects() {
    Config cfg = own();
    Map<String, ProjectMapping> out = new LinkedHashMap<>();
    for (String name : cfg.getSubsections("project")) {
      String owner = cfg.getString("project", name, "owner");
      String repo = cfg.getString("project", name, "repo");
      if (owner == null || repo == null) {
        // Half-configured mappings are skipped rather than guessed at; the
        // module logs them at startup.
        continue;
      }
      String prefix = cfg.getString("project", name, "branchPrefix");
      out.put(
          name,
          new ProjectMapping(
              name,
              owner,
              repo,
              prefix == null || prefix.isEmpty() ? "gerrit-archive" : prefix,
              java.util.List.of(cfg.getStringList("project", name, "branch"))));
    }
    return out;
  }

  /** Names of subsections that are missing required keys, for startup diagnostics. */
  public java.util.List<String> incompleteProjects() {
    Config cfg = own();
    java.util.List<String> bad = new java.util.ArrayList<>();
    for (String name : cfg.getSubsections("project")) {
      if (cfg.getString("project", name, "owner") == null
          || cfg.getString("project", name, "repo") == null) {
        bad.add(name);
      }
    }
    return bad;
  }

  public Config rawConfig() {
    return own();
  }

  public String pluginName() {
    return pluginName;
  }
}
